title: Life of Geek
description: Here are thoughts of a coder from India.

url: https://vasudevcoder.github.io/blog
baseurl: "/long-haul"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: vasudevcoder
   twitter: vasudevcoder
   email: vasudevcoder@gmail.com

google_analytics: "UA-58263416-1"
